## Basic implementation of the Dense class of Keras using numpy

In [1]:
import numpy as np

##### This is the kind of forward propagation implementation we are trying to mimic
    - layer_1 = Dense(units='3', activation='sigmoid')
    - a = layer_1(inp)
    - layer_1.get_weights()

##### In the __ _call_ __ method of the dense class:
- initialising self.weights with random floats if it was empty previously
- assuming inp to be of shape(1,n)
- assuming input to be of the form [x1,x2,1]
- each column of the wieghts array corresponds to a neuron in the layer
- the last row corresponds to the bias weights of the neuron

In [2]:
class dense:
    def __init__(self, units, activation):
        self.units=units
        self.activation=activation
        self.weights=np.array([], dtype=float)
    
    # fwd propagation
    def __call__(self, inp, seed=123):
        if(self.weights.size==0):
            #initialising weights only if no input had been passed previously
            rand_obj=np.random.RandomState(seed)
            self.weights=rand_obj.rand(inp.shape[1]+1, self.units)
        
        # adding bias element to the inp array
        inp=np.c_[inp, 1]
        
        # computing W.X
        a = np.matmul(inp,self.weights)
        
        #applying the activation
        if(self.activation=='sigmoid'):
            a=1/(1+np.exp(-a))
        if(self.activation=='None'):
            pass        
        return a
    def get_weights(self):
        return self.weights

In [3]:
layer_2=dense(units=5, activation='sigmoid')

In [4]:
b=layer_2(np.array([[5,6]]))
print(b)

[[0.99828078 0.99967919 0.99660418 0.99667131 0.99825298]]


In [5]:
layer_2.__dict__

{'units': 5,
 'activation': 'sigmoid',
 'weights': array([[0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897],
        [0.42310646, 0.9807642 , 0.68482974, 0.4809319 , 0.39211752],
        [0.34317802, 0.72904971, 0.43857224, 0.0596779 , 0.39804426]])}

In [6]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

In [7]:
layer_1=Dense(units=3, activation="sigmoid")

In [8]:
a=layer_1(np.array([[1,2,3,4]]))
print(a)

tf.Tensor([[0.72674143 0.44033107 0.035648  ]], shape=(1, 3), dtype=float32)


In [9]:
b=layer_1(np.array([[1,2,3,5]]))
print(b)

tf.Tensor([[0.71284425 0.565085   0.02413327]], shape=(1, 3), dtype=float32)
