In [1]:
import numpy as np
np.set_printoptions(precision=2) #no while printing the numpy arrays only 2 decimal places will be displayed

In [2]:
a=np.array([1,2,3,4,5]).reshape((5,1))
print(a)
b=a**2
print(b)
c=np.insert(a,1,b.reshape(1,5),axis=1)
print(c)

[[1]
 [2]
 [3]
 [4]
 [5]]
[[ 1]
 [ 4]
 [ 9]
 [16]
 [25]]
[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]
 [ 5 25]]


In [3]:
X_train1=np.sort([10,3,4,2,6,81], axis=0)
X_train1

array([ 2,  3,  4,  6, 10, 81])

In [4]:
#inserting columns to numpy arrays easy fix
x=np.array([1,2,3,4,5,6])
Y=np.c_[x, x**2, x**3]

Y

array([[  1,   1,   1],
       [  2,   4,   8],
       [  3,   9,  27],
       [  4,  16,  64],
       [  5,  25, 125],
       [  6,  36, 216]])

In [5]:
a=np.array([1,2,3,4,5,6,7])
print(a.shape)
print(a.reshape(1,-1))
print(a)
a=np.insert(a,7,8)
print(a)
b=np.array(a, dtype=int)
print(b)
c=np.array([2,1,3,5,4,6,7,8])
print(a==c)

(7,)
[[1 2 3 4 5 6 7]]
[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
[False False  True False False  True  True  True]


### Axis in numpy

In [6]:
b=np.reshape(np.arange(0,20), (4,5))
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
print(b.sum(axis=0))
print(b.sum(axis=1))

[30 34 38 42 46]
[10 35 60 85]


In [8]:
b.argmax(axis=0)    #compares the elements of a given column (operation performed on rows)

array([3, 3, 3, 3, 3], dtype=int64)

In [9]:
b.argmax(axis=1)    #compares the elements of a given row (operation performed on columns)

array([4, 4, 4, 4], dtype=int64)

In [ ]:
arr1=np.arange(0,40,2, dtype=int).reshape(-1,4)
arr2=np.arange(0,24,3, dtype=int).reshape(-1,4)
print(arr1)
print(arr2)
arr1_expanded = arr1[:,None, :]  # Shape (5, 1, 4)
arr2_expanded = arr2[None, :, :]  # Shape (1,2, 4)
#print(arr1_expanded)
# Compute XOR using broadcasting
result = np.bitwise_xor(arr1_expanded, arr2_expanded)  # Shape (5, 2, 4)
result

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]]
[[ 0  3  6  9]
 [12 15 18 21]]


array([[[ 0,  1,  2, 15],
        [12, 13, 22, 19]],

       [[ 8,  9, 10,  7],
        [ 4,  5, 30, 27]],

       [[16, 17, 18, 31],
        [28, 29,  6,  3]],

       [[24, 25, 26, 23],
        [20, 21, 14, 11]],

       [[32, 33, 34, 47],
        [44, 45, 54, 51]]])

In [11]:
arr1[0]^arr2[0]

array([ 0,  1,  2, 15])

In [12]:
np.bitwise_xor.outer(arr1[:,:,None, None], arr2[None,None, :,:]).shape

(5, 4, 1, 1, 1, 1, 2, 4)