# numpy
ML_developer's stack (1)

In [10]:
import numpy as np
a=[1,2,3,4,5,'6','a']
b=np.array(a[0:5]*3, int)
#c=np.array(a, int)#this gives error as 'a' can not be converted to int
print(b)
print(a*3)


[1 2 3 4 5 1 2 3 4 5 1 2 3 4 5]
[1, 2, 3, 4, 5, '6', 'a', 1, 2, 3, 4, 5, '6', 'a', 1, 2, 3, 4, 5, '6', 'a']


In [20]:
c=np.ones((2,3), dtype=int)
print(c)
d=np.zeros((4,5), dtype= float)
print(d)
e=np.full((3,4),5)
print(e)
f=np.empty((4))
print(f)

[[1 1 1]
 [1 1 1]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[1.24060000e-311 4.67296746e-307 5.45448473e-321 3.73479549e-312]


In [141]:
g=np.arange(1,10,1,dtype=int)
print(g)
h=np.linspace(1,10,50,dtype=float, endpoint=True)
print(h)

[1 2 3 4 5 6 7 8 9]
[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [46]:
i=np.random.rand(1,10)*100
print(i)

[[59.21383598  1.83850667 10.28743868 90.30262073 95.10597672 60.12835171
  27.50381294 40.96456404  7.5621697  48.92900752]]


In [48]:
arr1=np.arange(1,15, .5, dtype=float)
print(arr1.data)
print(arr1.shape)
print(arr1.dtype)
print(arr1.strides)


(28,)
float64
(8,)


In [50]:
arr1=np.full((3,4), 5)
print(arr1.data)
print(arr1.shape)
print(arr1.dtype)
print(arr1.strides)

(3, 4)
int32
(16, 4)


In [59]:
li=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr_2d=np.array(li,dtype=int)
print(li[1][0:3])
print(arr_2d[1][0:3])
print(arr_2d[1,0:3])

print(li[0:3][2])
print(arr_2d[0:3][2])
print(arr_2d[0:3,2])

[5, 6, 7]
[5 6 7]
[5 6 7]
[9, 10, 11, 12]
[ 9 10 11 12]
[ 3  7 11]


In [118]:
#np.random.randint(start,stop,order of matrix)
arr1=np.random.randint(1,20,5)
arr2=np.random.randint(1,20,5)
arr3=np.random.randint(1,30,(4,5))
print(arr1)
print(arr2)
print(arr3)

[ 5  2  4 10  5]
[13 17  8  4 18]
[[10 20  1  4 14]
 [16 18  9 12 20]
 [18 29 16 19 13]
 [16 18 18 18 22]]


In [119]:
print(arr1+arr2)
print(arr1*arr2)
print(arr1-arr2)
print(arr1/arr2)
print(arr1//arr2)
print(arr1**arr2)
print(arr1>arr2)
print(type(arr1<arr2))
print(arr1<arr2)
print(arr1==arr2)
print(np.logical_and(arr1,arr2))
print(np.logical_or(arr1,arr2))
print(np.logical_not(arr1))


[18 19 12 14 23]
[65 34 32 40 90]
[ -8 -15  -4   6 -13]
[0.38461538 0.11764706 0.5        2.5        0.27777778]
[0 0 0 2 0]
[1220703125     131072      65536      10000  766306777]
[False False False  True False]
<class 'numpy.ndarray'>
[ True  True  True False  True]
[False False False False False]
[ True  True  True  True  True]
[ True  True  True  True  True]
[False False False False False]


In [120]:
#boolean indexing
print(arr1)
print(arr2)
print(arr1[(arr1>arr2)&(arr1<18)])
print((arr1>arr2)&(arr1<18))
bool_arr= (arr1==arr2)
print(bool_arr)

[ 5  2  4 10  5]
[13 17  8  4 18]
[10]
[False False False  True False]
[False False False False False]


In [121]:
print(arr3)
bool_arr3=arr3>15#applying relational operations ot numpy arrays returns a boolean array
print(bool_arr3)
print(arr3[bool_arr3]) #passing boolean arrays to numpy array gives a numpy array of all those elements satisfying that condition
arr3[bool_arr3]=100
print(arr3)

[[10 20  1  4 14]
 [16 18  9 12 20]
 [18 29 16 19 13]
 [16 18 18 18 22]]
[[False  True False False False]
 [ True  True False False  True]
 [ True  True  True  True False]
 [ True  True  True  True  True]]
[20 16 18 20 18 29 16 19 16 18 18 18 22]
[[ 10 100   1   4  14]
 [100 100   9  12 100]
 [100 100 100 100  13]
 [100 100 100 100 100]]


In [122]:
arr4=np.random.randint(1,50,(4,5))
print(arr4)

[[32 48 14 12  9]
 [24 38 32 46  5]
 [ 9  3 48 22 35]
 [ 4 49 38 37 23]]


In [124]:
arr4[arr4<20]=100
print(arr4)

[[ 32  48 100 100 100]
 [ 24  38  32  46 100]
 [100 100  48  22  35]
 [100  49  38  37  23]]


In [133]:
print(arr4[0:4,4])
bool_arr4=(arr4[0:4,4]!=100)
print((arr4[0:4,4])[bool_arr4])



[100 100  35  23]
[35 23]


In [136]:
#updating values equal to 100 to 101 from the last column only
bool_arr4a=arr4[0:4,4]==100
arr4[(np.logical_not(bool_arr4a)),4]=101
print(arr4)

[[ 32  48 100 100 101]
 [ 24  38  32  46 101]
 [100 100  48  22 101]
 [100  49  38  37 101]]


In [137]:
num_Arr=np.array([0 for i in range(10)])
num_Arr=np.zeros(10,dtype=int)

In [160]:
numarr=np.random.randint(0,10,size=(4,4))
numarr1=np.random.randint(0,10,(4,4))
print(numarr)
print(numarr1)

[[6 8 8 4]
 [3 9 2 8]
 [8 4 8 4]
 [6 0 5 7]]
[[9 9 6 1]
 [8 7 9 8]
 [0 0 4 5]
 [9 3 7 9]]


In [165]:
num_arr1=np.array([1,2,0,4,4,0], dtype=int)
index_arr=np.where(num_arr1==0)
print(index_arr)
print(num_arr1.argmax())

(array([2, 5], dtype=int64),)
3
