In [1]:
import numpy as np
np.set_printoptions(precision=2) #no while printing the numpy arrays only 2 decimal places will be displayed

In [ ]:
a=np.array([1,2,3,4,5]).reshape((5,1))
print(a)
b=a**2
print(b)
c=np.insert(a,1,b.reshape(1,5),axis=1)
print(c)

[[1]
 [2]
 [3]
 [4]
 [5]]
[[ 1]
 [ 4]
 [ 9]
 [16]
 [25]]
[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]
 [ 5 25]]


In [9]:
X_train1=np.sort([10,3,4,2,6,81], axis=0)
X_train1

array([ 2,  3,  4,  6, 10, 81])

In [10]:
#inserting columns to numpy arrays easy fix
x=np.array([1,2,3,4,5,6])
Y=np.c_[x, x**2, x**3]

Y

array([[  1,   1,   1],
       [  2,   4,   8],
       [  3,   9,  27],
       [  4,  16,  64],
       [  5,  25, 125],
       [  6,  36, 216]])

In [31]:
a=np.array([1,2,3,4,5,6,7])
print(a.shape)
print(a.reshape(1,-1))
print(a)
a=np.insert(a,7,8)
print(a)
b=np.array(a, dtype=int)
print(b)
c=np.array([2,1,3,5,4,6,7,8])
print(a==c)

(7,)
[[1 2 3 4 5 6 7]]
[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
[False False  True False False  True  True  True]
