## np.random method:
- the random numbers/sequences generated by methods of the np.random module are not truly random i.e they are generated by providing a initial key value(seed) to a mathematical algorithm and thus these sequences can be repeated.
- i.e. the seed given to the random number generator decides the sequence in which it will generate random numbers
- truly random numbers can only be generated by using natural phenonmenons. eg- using atmospheric noise to generate numbers
1. np.random.rand(array size):
- generates a random number between 0 and 1 from a uniform distribution
2. np.random.randn(array size):
- generates random numbers with a specific mean and stnadard deviation
3. np.random.seed(seed_val) and np.random.RandomState(seed_val):
- the random.seed(seed_val) method sets the seed value of the global numpy random number generator. This can be problamatic if some other library's function is also using the np.random functions simultaneously.
- while, the random.RandomState() method creates a local instsance of the global random number generator with the seed value as specified.
- thus for large projects it is adivsed to use random.RandomState() mehtod.

In [1]:
import numpy as np

In [5]:
arr1=np.random.rand(10,3)
arr1

#creates a 10x3 array of random floats between 0 and 1

array([[0.75427811, 0.85460543, 0.15939467],
       [0.79899274, 0.38778405, 0.17312865],
       [0.32178917, 0.92255375, 0.46084304],
       [0.22911289, 0.87341741, 0.33181584],
       [0.81598403, 0.15834304, 0.11408286],
       [0.30075032, 0.82930437, 0.23764898],
       [0.02329397, 0.40618784, 0.17347501],
       [0.80858404, 0.19186298, 0.28736652],
       [0.86219496, 0.30793523, 0.6366043 ],
       [0.96134056, 0.68837291, 0.92473214]])

In [4]:
arr2=2*np.random.randn(3,4)+10
arr2

#creates a 3x4 array with its elements being random numbers from a normal distribution with mean 10 and std dev as 2

array([[11.62075221,  8.25401707,  8.95726996, 14.3861452 ],
       [ 9.8948174 ,  8.15188178,  9.05058181, 11.61428109],
       [ 8.71111755,  8.65767755,  9.01573925, 11.43564688]])

In [5]:
np.random.seed(3) #sets the seed of the global numpy random number generator to 3
print(np.random.rand(3,2))
print(np.random.rand(3,2))
print(np.random.rand(3,2))

[[0.5507979  0.70814782]
 [0.29090474 0.51082761]
 [0.89294695 0.89629309]]
[[0.12558531 0.20724288]
 [0.0514672  0.44080984]
 [0.02987621 0.45683322]]
[[0.64914405 0.27848728]
 [0.6762549  0.59086282]
 [0.02398188 0.55885409]]


In [6]:
np.random.seed(3) #sets the seed of the global numpy random number generator to 3
print(np.random.rand(3,1))
print(np.random.rand(3,1))
print(np.random.rand(3,1))

#note that the first nine numbers of both the array sets are same 

[[0.5507979 ]
 [0.70814782]
 [0.29090474]]
[[0.51082761]
 [0.89294695]
 [0.89629309]]
[[0.12558531]
 [0.20724288]
 [0.0514672 ]]


In [7]:
rng_obj=np.random.RandomState(3)
print(rng_obj.rand(3))
print(rng_obj.rand(3))
print(rng_obj.rand(3))
print(rng_obj.rand(3))


[0.5507979  0.70814782 0.29090474]
[0.51082761 0.89294695 0.89629309]
[0.12558531 0.20724288 0.0514672 ]
[0.44080984 0.02987621 0.45683322]


In [17]:
rng_obj2=np.random.RandomState(3)
print(rng_obj2.rand(3)) #everytime the output will be same as the seed value for the local random object is fixed

[0.5507979  0.70814782 0.29090474]


In [18]:
a=np.random.randint(low=10, high=100, size=(2,3))
a

array([[76, 12, 73],
       [70, 11, 61]])

In [19]:
#shuffling an array randomly

r=np.arange(0,100,1)
rand_obj=np.random.RandomState(123)
rand_obj.shuffle(r)
print(r)


[ 8 70 82 28 63  0  5 50 81  4 23 65 76 60 24 42 77 38 56 75 35 88 19 29
 31 91 85  9 53 41 21 90 33 69 84 87 95 97 62 12 20 89 37 59  1 74 11 79
 14 54 16 26 51 45  6 98 30 44 72 43 15 94 18 13 22 10 58 71 64  3 40 34
 27 52  7 48 61 93 99 39  2 67 55 49 68 80 36 78 96 25 46 32 73 47 86 57
 83 17 92 66]
