## np.random method:
- the random numbers/sequences generated by methods of the np.random module are not truly random i.e they are generated by providing a initial key value(seed) to a mathematical algorithm and thus these sequences can be repeated.
- i.e. the seed given to the random number generator decides the sequence in which it will generate random numbers
- truly random numbers can only be generated by using natural phenonmenons. eg- using atmospheric noise to generate numbers
1. np.random.rand(array size):
- generates a random number between 0 and 1 from a uniform distribution
2. np.random.randn(array size):
- generates random numbers with a specific mean and stnadard deviation
3. np.random.seed(seed_val) and np.random.RandomState(seed_val):
- the random.seed(seed_val) method sets the seed value of the global numpy random number generator. This can be problamatic if some other library's function is also using the np.random functions simultaneously.
- while, the random.RandomState() method creates a local instsance of the global random number generator with the seed value as specified.
- thus for large projects it is adivsed to use random.RandomState() mehtod.
4. np.random.

In [2]:
import numpy as np

In [4]:
arr1=np.random.rand(10,3)
arr1

#creates a 10x3 array of random floats between 0 and 1

array([[0.54655178, 0.67799189, 0.05780129],
       [0.18816427, 0.67509478, 0.12544417],
       [0.52498867, 0.97353977, 0.72818418],
       [0.85821428, 0.86369993, 0.92986995],
       [0.56904195, 0.61170583, 0.13557631],
       [0.18655718, 0.22835313, 0.49782185],
       [0.58402649, 0.05740468, 0.16868616],
       [0.58118975, 0.55155147, 0.55593652],
       [0.12809821, 0.56489892, 0.2937253 ],
       [0.1893691 , 0.77081275, 0.68442287]])

In [5]:
arr2=2*np.random.randn(3,4)+10
arr2

#creates a 3x4 array with its elements being random numbers from a normal distribution with mean 10 and std dev as 2

array([[ 8.43852831, 13.67456439,  6.70914724,  6.11249172],
       [ 9.03093879,  9.69750479, 11.89774021, 11.45770085],
       [ 5.41698766,  6.69657614, 13.14575295, 13.03600683]])

In [8]:
np.random.seed(3) #sets the seed of the global numpy random number generator to 3
print(np.random.rand(3,2))
print(np.random.rand(3,2))
print(np.random.rand(3,2))

[[0.5507979  0.70814782]
 [0.29090474 0.51082761]
 [0.89294695 0.89629309]]
[[0.12558531 0.20724288]
 [0.0514672  0.44080984]
 [0.02987621 0.45683322]]
[[0.64914405 0.27848728]
 [0.6762549  0.59086282]
 [0.02398188 0.55885409]]


In [9]:
np.random.seed(3) #sets the seed of the global numpy random number generator to 3
print(np.random.rand(3,1))
print(np.random.rand(3,1))
print(np.random.rand(3,1))

#note that the first nine numbers of both the array sets are same 

[[0.5507979 ]
 [0.70814782]
 [0.29090474]]
[[0.51082761]
 [0.89294695]
 [0.89629309]]
[[0.12558531]
 [0.20724288]
 [0.0514672 ]]


In [13]:
rng_obj=np.random.RandomState(3)
print(rng_obj.rand(3))
print(rng_obj.rand(3))
print(rng_obj.rand(3))
print(rng_obj.rand(3))


[0.5507979  0.70814782 0.29090474]
[0.51082761 0.89294695 0.89629309]
[0.12558531 0.20724288 0.0514672 ]
[0.44080984 0.02987621 0.45683322]


In [15]:
rng_obj2=np.random.RandomState(3)
print(rng_obj2.rand(3))

[0.5507979  0.70814782 0.29090474]
